version: "3"

services:
  dev:
    image: python-backend-lecture-3-hw:latest
    build:
      context: .
      dockerfile: Dockerfile  
      target: dev
    restart: always

  local:
    image: python-backend-lecture-3-hw-local:latest
    build:
      context: .
      dockerfile: Dockerfile  
      target: local
    restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
